#!/bin/bash
# for multicore machine NOTE edit to batch by < number of available cores
# R --slave --vanilla --args < ../R/multirunner.R ETH  & R --slave --vanilla --args < ../R/multirunner.R KEN  & R --slave --vanilla --args < ../R/multirunner.R LSO  & R --slave --vanilla --args < ../R/multirunner.R MOZ  & R --slave --vanilla --args < ../R/multirunner.R MWI  & R --slave --vanilla --args < ../R/multirunner.R NGA & R --slave --vanilla --args < ../R/multirunner.R SWZ  & R --slave --vanilla --args < ../R/multirunner.R TZA  & R --slave --vanilla --args < ../R/multirunner.R UGA  & R --slave --vanilla --args < ../R/multirunner.R ZAF  & R --slave --vanilla --args < ../R/multirunner.R ZMB  & R --slave --vanilla --args < ../R/multirunner.R ZWE


# R --slave --vanilla --args < ../R/multirunner.R ETH EPTBlo & R --slave --vanilla --args < ../R/multirunner.R KEN EPTBlo & R --slave --vanilla --args < ../R/multirunner.R LSO EPTBlo & R --slave --vanilla --args < ../R/multirunner.R MOZ EPTBlo & R --slave --vanilla --args < ../R/multirunner.R MWI EPTBlo & R --slave --vanilla --args < ../R/multirunner.R NGA EPTBlo & R --slave --vanilla --args < ../R/multirunner.R SWZ EPTBlo & R --slave --vanilla --args < ../R/multirunner.R TZA EPTBlo & R --slave --vanilla --args < ../R/multirunner.R UGA EPTBlo & R --slave --vanilla --args < ../R/multirunner.R ZAF EPTBlo & R --slave --vanilla --args < ../R/multirunner.R ZMB EPTBlo & R --slave --vanilla --args < ../R/multirunner.R ZWE EPTBlo


# R --slave --vanilla --args < ../R/multirunner.R ETH EPTBhi & R --slave --vanilla --args < ../R/multirunner.R KEN EPTBhi & R --slave --vanilla --args < ../R/multirunner.R LSO EPTBhi & R --slave --vanilla --args < ../R/multirunner.R MOZ EPTBhi & R --slave --vanilla --args < ../R/multirunner.R MWI EPTBhi & R --slave --vanilla --args < ../R/multirunner.R NGA EPTBhi & R --slave --vanilla --args < ../R/multirunner.R SWZ EPTBhi & R --slave --vanilla --args < ../R/multirunner.R TZA EPTBhi & R --slave --vanilla --args < ../R/multirunner.R UGA EPTBhi & R --slave --vanilla --args < ../R/multirunner.R ZAF EPTBhi & R --slave --vanilla --args < ../R/multirunner.R ZMB EPTBhi & R --slave --vanilla --args < ../R/multirunner.R ZWE EPTBhi

R --slave --vanilla --args < ../R/multirunner.R ETH INF1014 & R --slave --vanilla --args < ../R/multirunner.R KEN INF1014 & R --slave --vanilla --args < ../R/multirunner.R LSO INF1014 & R --slave --vanilla --args < ../R/multirunner.R MOZ INF1014 & R --slave --vanilla --args < ../R/multirunner.R MWI INF1014 & R --slave --vanilla --args < ../R/multirunner.R NGA INF1014 & R --slave --vanilla --args < ../R/multirunner.R SWZ INF1014 & R --slave --vanilla --args < ../R/multirunner.R TZA INF1014 & R --slave --vanilla --args < ../R/multirunner.R UGA INF1014 & R --slave --vanilla --args < ../R/multirunner.R ZAF INF1014 & R --slave --vanilla --args < ../R/multirunner.R ZMB INF1014 & R --slave --vanilla --args < ../R/multirunner.R ZWE INF1014
